homework_04/Models/Movie.cs
namespace homework_04.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Poster { get; set; }
        public string Director { get; set; }
        public string Style { get; set; }
        public string ShortDescription { get; set; }
        public List<Session> Sessions { get; set; }
    }
}

homework_04/Models/Session.cs
namespace homework_04.Models
{
    public class Session
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public TimeOnly Time { get; set; }
    }
}

homework_04/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace homework_04.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

homework_04/Pages/Index.cshtml.cs
using homework_04.Models;
using homework_04.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public List<Movie> Movies { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            MovieService.Seed();

            return RedirectToPage("/Movies/Index");
        }
    }
}

homework_04/Pages/Movies/Add.cshtml.cs
using homework_04.Models;
using homework_04.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages.Movies
{
    public class AddModel : PageModel
    {
        public Movie Movie { get; set; }

        public void OnGet()
        {
        }

        public IActionResult OnPost(Movie movie)
        {
            Movie = movie;

            if (String.IsNullOrEmpty(Movie.Title) ||
                String.IsNullOrEmpty(Movie.Poster) ||
                String.IsNullOrEmpty(Movie.Director) ||
                String.IsNullOrEmpty(Movie.Style) ||
                String.IsNullOrEmpty(Movie.ShortDescription))
            {
                return Page();
            }

            MovieService.AddMovie(Movie);
                
            return RedirectToPage("Index");
        }
    }
}

homework_04/Pages/Movies/Edit.cshtml.cs
using homework_04.Models;
using homework_04.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages.Movies
{
	public class EditModel : PageModel
	{
		public Movie Movie { get; set; }

		public void OnGet(int id)
		{
			Movie = MovieService.GetMovieById(id);
		}

		public IActionResult OnPost(int id, Movie movie)
		{
			Movie = movie;
			Movie.Id = id;

			if (String.IsNullOrEmpty(Movie.Title) ||
				String.IsNullOrEmpty(Movie.Poster) ||
				String.IsNullOrEmpty(Movie.Director) ||
				String.IsNullOrEmpty(Movie.Style) ||
				String.IsNullOrEmpty(Movie.ShortDescription))
			{
				return Page();
			}

			MovieService.UpdateMovie(Movie);

			return RedirectToPage("Index");
		}
	}
}

homework_04/Pages/Movies/Index.cshtml.cs
using homework_04.Models;
using homework_04.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages.Movies
{
    public class IndexModel : PageModel
    {
        public List<Movie> Movies { get; set; }

        public void OnGet()
        {
            Movies = MovieService.GetAllMovies();
        }

        public IActionResult OnPostSearch(string searchValue)
        {
            if (searchValue == null)
            {
                Movies = MovieService.GetAllMovies();

                return Page();
            }

            Movies = MovieService.FindMovieByTitle(searchValue);

            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            Movies = MovieService.GetAllMovies();

            MovieService.DeleteMovieById(id);

            return Page();
        }
    }
}

homework_04/Pages/Movies/Info.cshtml.cs
using homework_04.Models;
using homework_04.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages.Movies
{
    public class InfoModel : PageModel
    {
        public Movie Movie { get; set; }
        
        public void OnGet(int id)
        {
            Movie = MovieService.GetMovieById(id);
        }

        public IActionResult OnPostDeleteSession(int movieId, int sessionId)
        {
            MovieService.DeleteSessionById(movieId, sessionId);
            Movie = MovieService.GetMovieById(movieId);

            return Page();
        }
    }
}

homework_04/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace homework_04.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

homework_04/Pages/Index.cshtml
@page "{searchValue?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Фільми</h1>
    
    <form method="post" class="ms-2">
        <input class="form-control m-1" name="searchValue" placeholder="Введіть назву фільму..." />
        <button class="btn btn-primary m-1">Пошук</button>
    </form>

    <div class="container text-center">
        @for(int i = 0; i < Model.Movies.Count; i += 3)
        {
            <div class="row row-cols-3">
                @for (int j = 0; j < 3 && i + j < Model.Movies.Count; j++)
                {
                        <div class="col">
                            <div class="card" style="width: 26rem;">
                                <img src=@Model.Movies[i + j].Poster class="card-img-top" alt="@Model.Movies[i + j].Title">
                        
                                <div class="card-body">
                                    <h5 class="card-title">@Model.Movies[i + j].Title</h5>
                                    <p class="card-text">@Model.Movies[i + j].Style</p>
                                    <a asp-page="Movies/Info" asp-route-id="@((i + j) + 1)" class="btn btn-primary">Detail</a>
                                </div>
                            </div>
                        </div>
                }
            </div>
        }
    </div>
</div>

homework_04/Pages/Movies/Add.cshtml
@page
@model homework_04.Pages.Movies.AddModel
@{
}

<form method="post">
	<div>
		<label class="form-label m-1" asp-for="Movie.Title">Назва</label>
		<input class="form-control m-1" asp-for="Movie.Title" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Poster">Постер</label>
		<input class="form-control m-1" asp-for="Movie.Poster" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Director">Режисер</label>
		<input class="form-control m-1" asp-for="Movie.Director" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Style">Жанр</label>
		<input class="form-control m-1" asp-for="Movie.Style" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.ShortDescription">Короткий опис</label>
		<input class="form-control m-1" asp-for="Movie.ShortDescription" />
	</div>

	<div>
		<button class="btn btn-primary m-1">Додати</button>
	</div>
</form>

homework_04/Pages/Movies/Edit.cshtml
@page "{id}"
@model homework_04.Pages.Movies.EditModel
@{
}

<form method="post">
	<div>
		<label class="form-label m-1" asp-for="Movie.Title">Назва</label>
		<input class="form-control m-1" asp-for="Movie.Title" value="@Model.Movie.Title" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Poster">Постер</label>
		<input class="form-control m-1" asp-for="Movie.Poster" value="@Model.Movie.Poster" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Director">Режисер</label>
		<input class="form-control m-1" asp-for="Movie.Director" value="@Model.Movie.Director" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.Style">Жанр</label>
		<input class="form-control m-1" asp-for="Movie.Style" value="@Model.Movie.Style" />
	</div>

	<div>
		<label class="form-label m-1" asp-for="Movie.ShortDescription">Короткий опис</label>
		<input class="form-control m-1" asp-for="Movie.ShortDescription" value="@Model.Movie.ShortDescription" />
	</div>

	<div>
		<button class="btn btn-primary m-1" asp-route-id="@Model.Movie.Id">Зберегти</button>
	</div>
</form>

homework_04/Pages/Movies/Index.cshtml
@page "{searchValue?}"
@model homework_04.Pages.Movies.IndexModel
@{
}

<div class="text-center">
    <h1>Фільми</h1>

    <form method="post" class="ms-2">
        <input class="form-control m-1" name="searchValue" placeholder="Введіть назву фільму..." />
        <button class="btn btn-primary m-1" asp-page-handler="Search">Пошук</button>
    </form>

    <div>
        <a class="btn btn-primary m-1" asp-page="Add">Додати Фільм</a>
    </div>

    <div class="container text-center">
        @for (int i = 0; i < Model.Movies.Count; i += 3)
        {
            <div class="row row-cols-3">
                @for (int j = 0; j < 3 && i + j < Model.Movies.Count; j++)
                {
                    <div class="col">
                        <div class="card m-1" style="width: 26rem;">
                            <img src=@Model.Movies[i + j].Poster class="card-img-top" alt="@Model.Movies[i + j].Title">

                            <div class="card-body">
                                <h5 class="card-title">@Model.Movies[i + j].Title</h5>
                                <p class="card-text">@Model.Movies[i + j].Style</p>
                                <form method="post">
                                    <a asp-page="Info" asp-route-id="@((i + j) + 1)" class="btn btn-primary">Детальніше</a>
                                    <button asp-page-handler="Delete" asp-route-id="@((i + j) + 1)" class="btn btn-danger">Видалити</button>
                                </form>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
    </div>
</div>

homework_04/Pages/Movies/Info.cshtml
@page "{id:int}"
@model homework_04.Pages.Movies.InfoModel
@{
}

<div class="container">
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <img src="@Model.Movie.Poster" class="img-thumbnail" alt="@Model.Movie.Title">
            </div>

            <div class="col">
                <h2>@Model.Movie.Title</h2>
                <p>@Model.Movie.Director</p>
                <p>@Model.Movie.Style</p>
                <p>@Model.Movie.ShortDescription</p>
            </div>

            <div>
                <a class="btn btn-primary m-1 text-end" asp-page="Edit" asp-route-id="@Model.Movie.Id">Редагувати</a>
            </div>
        </div>

        <h2>Сеанси</h2>

        <div class="container">
            <a class="btn btn-primary m-1 text-start" asp-page="../Sessions/Add" asp-route-id="@Model.Movie.Id">Додати</a>
        </div>

        <div class="col">
            <table class="table table-info">
                <thead>
                    <tr>
                        <th scope="col">Ід</th>
                        <th scope="col">Дата</th>
                        <th scope="col">Час</th>
                        <th scope="col">Взаємодія</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach(var session in Model.Movie.Sessions)
                    {
                        <tr>
                            <th scope="row">@session.Id</th>
                            <td>@session.Date.ToShortDateString()</td>
                            <td>@session.Time</td>
                            <td>
                                <form method="post">
                                    <a class="btn btn-primary m-1" asp-page="../Sessions/Edit" asp-route-movieId="@Model.Movie.Id" asp-route-sessionId="@session.Id">Редагувати</a>
                                    <button class="btn btn-danger m-1" asp-page-handler="DeleteSession" asp-route-movieId="@Model.Movie.Id" asp-route-sessionId="@session.Id">Видалити</button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

homework_04/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - homework_04</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/homework_04.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">homework_04</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - homework_04 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>